version: "3.0"

services:
  appx-builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: base-dev
    env_file:
      - .env
      - .env.development
      - .env.local
    ports:
      - "4000:4000"
    environment:
      - TZ=Europe/Paris
      - NODE_ENV=development
    volumes:
      - .:/data/
